### ISSUE TITLE
Boost Fails 

### ISSUE THREAD

**Issue by Nammi12** [opencog/moses#104]
I am running my command to compile Moses ToolKit on Ubuntu 20.04 using the following command and get the below issue 

./bjam --with-cmph=/home/namrata/smt/cmph-2.0 -j4

Error : 
XMLRPC-C: USING VERSION 1.33.14 FROM /usr/local
BUILDING MOSES SERVER!
Performing configuration checks

    - Shared Boost             : no
    - Static Boost             : yes
BUILDING MOSES2 SERVER!
Building Moses2
...patience...
...patience...
...found 7284 targets...
...updating 72 targets...
gcc.link moses-cmd/bin/gcc-4.8/release/link-static/threading-multi/moses
/usr/bin/ld: moses/bin/gcc-4.8/release/link-static/threading-multi/libmoses.a(InMemoryPerSentenceOnDemandLM.o): in function `Moses::InMemoryPerSentenceOnDemandLM::InitializeForInput(boost::shared_ptr<Moses::TranslationTask> const&)':
InMemoryPerSentenceOnDemandLM.cpp:(.text+0x39f): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: moses/bin/gcc-4.8/release/link-static/threading-multi/libmoses.a(Parameter.o): in function `Moses::Parameter::Parameter()':
Parameter.cpp:(.text+0x137e): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: Parameter.cpp:(.text+0x17e7): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: Parameter.cpp:(.text+0x1a01): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: Parameter.cpp:(.text+0x1ff7): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: Parameter.cpp:(.text+0x266c): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: moses/bin/gcc-4.8/release/link-static/threading-multi/libmoses.a(Parameter.o):Parameter.cpp:(.text+0x2982): more undefined references to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)' follow
collect2: error: ld returned 1 exit status

    "g++" -L"/home/namrata/smt/cmph-2.0/lib" -L"/home/namrata/smt/cmph-2.0/lib64" -L"/usr/local/lib" -Wl,-R -Wl,"/home/namrata/smt/cmph-2.0/lib" -Wl,-R -Wl,"/home/namrata/smt/cmph-2.0/lib64" -Wl,-R -Wl,"/usr/local/lib" -Wl,-rpath-link -Wl,"/home/namrata/smt/cmph-2.0/lib" -Wl,-rpath-link -Wl,"/home/namrata/smt/cmph-2.0/lib64" -Wl,-rpath-link -Wl,"/usr/local/lib" -o "moses-cmd/bin/gcc-4.8/release/link-static/threading-multi/moses" -Wl,--start-group "moses-cmd/bin/gcc-4.8/release/link-static/threading-multi/Main.o" "moses/bin/gcc-4.8/release/link-static/threading-multi/libmoses.a" "probingpt/bin/gcc-4.8/release/link-static/threading-multi/libprobingpt.a"  -Wl,-Bstatic -lboost_filesystem -lboost_iostreams -lz -lboost_filesystem -lboost_iostreams -lcmph -llzma -lbz2 -lxmlrpc_xmltok -lxmlrpc_xmlparse -lxmlrpc_util -lxmlrpc_server_abyss++ -lxmlrpc_server_abyss -lxmlrpc_server++ -lxmlrpc_server -lxmlrpc_abyss -lxmlrpc++ -lxmlrpc -ltcmalloc_minimal -lboost_thread -lboost_system -lboost_serialization -lboost_program_options -lz -Wl,-Bdynamic -lSegFault -lrt -Wl,--end-group -pthread 

...failed gcc.link moses-cmd/bin/gcc-4.8/release/link-static/threading-multi/moses...
gcc.link moses-cmd/bin/gcc-4.8/release/link-static/threading-multi/lmbrgrid
/usr/bin/ld: moses/bin/gcc-4.8/release/link-static/threading-multi/libmoses.a(InMemoryPerSentenceOnDemandLM.o): in function `Moses::InMemoryPerSentenceOnDemandLM::InitializeForInput(boost::shared_ptr<Moses::TranslationTask> const&)':
InMemoryPerSentenceOnDemandLM.cpp:(.text+0x39f): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: moses/bin/gcc-4.8/release/link-static/threading-multi/libmoses.a(Parameter.o): in function `Moses::Parameter::Parameter()':
Parameter.cpp:(.text+0x137e): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: Parameter.cpp:(.text+0x17e7): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: Parameter.cpp:(.text+0x1a01): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: Parameter.cpp:(.text+0x1ff7): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: Parameter.cpp:(.text+0x266c): undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/usr/bin/ld: moses/bin/gcc-4.8/release/link-static/threading-multi/libmoses.a(Parameter.o):Parameter.cpp:(.text+0x2982): more undefined references to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)' follow
collect2: error: ld returned 1 exit status

   .............................
...failed gcc.link moses/LM/bin/BackwardTest.test/gcc-4.8/release/link-static/threading-multi/BackwardTest...
...skipped <pmoses/LM/bin/BackwardTest.test/gcc-4.8/release/link-static/threading-multi>BackwardTest.run for lack of <pmoses/LM/bin/BackwardTest.test/gcc-4.8/release/link-static/threading-multi>BackwardTest...
...failed updating 65 targets...
...skipped 7 targets...
The build failed.  If you need support, run:
  ./jam-files/bjam --with-cmph=/home/namrata/smt/cmph-2.0 -j4 --debug-configuration -d2 |gzip >build.log.gz
then attach build.log.gz to your e-mail.
You MUST do 3 things before sending to the mailing list:
   1. Subscribe to the mailing list at http://mailman.mit.edu/mailman/listinfo/moses-support
   2. Attach build.log.gz to your e-mail
   3. Say what is the EXACT command you executed when you got the error
ERROR

**Comment by linas** [comment]
I'm closing this, because you have the wrong "moses" -- you are talking about a language system called "moses-smt". This moses is completely unrelated, its a machine learning system that happens to have the same name.

Also: I see the string "gcc-4.8" in your error messages. This is an extremely old compiler -- maybe ten years old, now. You should almost certainly update to something modern, or clean out whatever location that old stuff is coming from. That might make your bug go aaway.
