### ISSUE TITLE
All Unit tests failing on buildbot, why?

### ISSUE THREAD

**Issue by AmeBel** [opencog/moses#11]
### Unit tests report
```
0% tests passed, 35 tests failed out of 35

Total Test time (real) =   0.18 sec
```
more @ http://buildbot.opencog.org:8010/builders/moses_master_trusty/builds/0/steps/test/logs/stdio

The installed dependencies are https://github.com/opencog/docker/blob/master/opencog/base/Dockerfile#L8-L14 (basically all the opencog's system dependencies with the exception of link-grammar) and cogutils.

Are there any dependencies missing or configurations required for moses?

**Comment by ngeiswei** [comment]
No idea, is there a way to see the individual test outputs?

**Comment by AmeBel** [comment]
http://buildbot.opencog.org:8010/builders/atomspace_master_trusty/builds/7/steps/test/logs/testlog

**Comment by AmeBel** [comment]
Testlog
http://buildbot.opencog.org:8010/builders/moses_master_trusty/builds/0/steps/test/logs/testlog

**Comment by ngeiswei** [comment]
Looks like cogutils isn't properly installed.

**Comment by AmeBel** [comment]
would moses build without cogutils? http://buildbot.opencog.org:8010/builders/moses_master_trusty/builds/1/steps/compile/logs/stdio

**Comment by AmeBel** [comment]
just run the test locally after installing cogutils, same thing.

**Comment by ngeiswei** [comment]
I don't have that problem locally. Have you tried to run sudo ldconfig?

**Comment by AmeBel** [comment]
that was it. Thanks
