### ISSUE TITLE
Moses result as scheme

### ISSUE THREAD

**Issue by mahletA** [opencog/moses#46]
Is there any way to print out moses results directly from the command line in a scheme format rather than a python snippet or a combo function? It is possible to do this using pymoses.But why isn't this possible form the command line?

**Comment by ngeiswei** [comment]
```
moses --help | grep 'output-format' -A 1
  --output-format arg (=combo)          Supported output formats are combo, 
                                        python and scheme
```

**Comment by mahletA** [comment]
Thank you!
