### ISSUE TITLE
Is there a way to poll the progress of a running MOSES process?

### ISSUE THREAD

**Issue by Habush** [opencog/moses#59]
I am currently using Moses on a project and it takes about two hours to finish a single run. I was wondering if there is any way we can track the progress of the Moses run so that we can monitor it and display the progress result to users.

**Comment by ngeiswei** [comment]
Sure, MOSES logs its progress in `moses.log` while running. You may change the log level with option `-l`. For more info you invoke MOSES help `moses --help`. There is also a man page.

**Comment by Habush** [comment]
Thanks for the reply.

So is there any indicator in the log info that specifies the progress in a percentage or the current number of evaluation since Moses started?

**Comment by linas** [comment]
Not only is progress written to the log file, but there is a large/huge amount of info written there, in such a way that you can constantly and continually monitor the best and greatest results, without ever waiting for moses to "finish". Effectively, you can make it run forever, and always get the current best results, together with a measure of how good they are, how much better they are than the last results you'd looked at.

For many cases, this is the "best" way to run moses: just run it continuously, and stop it whenever the results are "good enough", and you need to free up  the CPU/RAM resources for something else.
