### ISSUE TITLE
remove log output from stdout

### ISSUE THREAD

**Issue by mjsduncan** [opencog/moses#64]
is there any way to turn of the log output from the stdout stream?  it breaks pipes using the moses binary.

**Comment by ngeiswei** [comment]
@mjsduncan, yes you can turn off stdout either via the C++ API

```c++
logger().set_print_to_stdout_flag(false);
```

or via the Scheme API

```scheme
(cog-logger-set-stdout! #f)
```

However my default that's what `moses` should do. In which context do get that problem?

**Comment by mjsduncan** [comment]
thanks!  it broke my R wrapper which takes the output directly from the binary.  if this is standard now shouldn't saving results to file be built in?  right now it's an optional flag.

**Comment by mjsduncan** [comment]
turning it off via the command line would be ideal.

**Comment by ngeiswei** [comment]
Oh, so you don't mean the logging system I think, just the output results, the candidates and their scores, right?

Can't you just redirect moses' output to /dev/null?

**Comment by ngeiswei** [comment]
Actually there's an option, `-o`, is that doing what you need?

**Comment by ngeiswei** [comment]
@mjsduncan what do you mean by "log lines"? Do you mean what is written in `moses.log`? Like
```
[2018-10-17 09:09:56:688] [INFO] moses version 3.6.10
[2018-10-17 09:09:56:688] [INFO] hostname: sofia-desktop
[2018-10-17 09:09:56:688] [INFO] Command line: moses -Hpa -k4 -m10000 -j4
[2018-10-17 09:09:56:688] [INFO] Alphabet size = 7 output = boolean
[2018-10-17 09:09:56:688] [INFO] BScore complexity ratio = 3.5
[2018-10-17 09:09:56:689] [INFO] Cache composite scores
[2018-10-17 09:09:56:689] [INFO] Inferred target score = 0
```
?

This shouldn't pollute the stdout, if it does, something is weird.

**Comment by mjsduncan** [comment]
those are the lines i'm talking about.  after testing further this is an R bug, the R function that runs shell binaries is now somehow pulling the log output as well as the final results from what is supposed to only be the "stdout" source.  sorry for not checking this first.
